server {
    listen 80;
    server_name api.katisha.online;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.katisha.online;

    ssl_certificate     /etc/letsencrypt/live/api.katisha.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.katisha.online/privkey.pem;

    location / {
        set $upstream http://api-gw:8081;
        proxy_pass $upstream;
    }
}
